ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'CURSO_PAGAMENTO_PENDENTE';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'CURSO_PAGAMENTO_PROCESSANDO';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'CURSO_PAGAMENTO_APROVADO';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'CURSO_PAGAMENTO_RECUSADO';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'CURSO_PAGAMENTO_CANCELADO';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'CURSO_PAGAMENTO_ESTORNADO';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'CURSO_PAGAMENTO_CONTESTADO';
