CREATE TYPE "CursosCertificados" AS ENUM (
  'SEM_CERTIFICADO',
  'PARTICIPACAO',
  'CONCLUSAO',
  'APROVEITAMENTO',
  'COMPETENCIA'
);

CREATE TYPE "CursosCertificadosTipos" AS ENUM (
  'DIGITAL',
  'IMPRESSO',
  'DIGITAL_E_IMPRESSO',
  'VERIFICAVEL'
);
