-- AlterEnum
ALTER TYPE "CursosNotasTipo" ADD VALUE IF NOT EXISTS 'ATIVIDADE';
ALTER TYPE "CursosNotasTipo" ADD VALUE IF NOT EXISTS 'PROJETO';
ALTER TYPE "CursosNotasTipo" ADD VALUE IF NOT EXISTS 'SEMINARIO';
ALTER TYPE "CursosNotasTipo" ADD VALUE IF NOT EXISTS 'PARTICIPACAO';
ALTER TYPE "CursosNotasTipo" ADD VALUE IF NOT EXISTS 'SIMULADO';
ALTER TYPE "CursosNotasTipo" ADD VALUE IF NOT EXISTS 'BONUS';
ALTER TYPE "CursosNotasTipo" ADD VALUE IF NOT EXISTS 'OUTRO';
