ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'TURMA_ESTRUTURA_PENDENTE_24H';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'TURMA_INICIO_BLOQUEADO_ESTRUTURA';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'TURMA_INICIO_REPROGRAMADO';
ALTER TYPE "NotificacaoTipo" ADD VALUE IF NOT EXISTS 'TURMA_NOVA_DATA_CONFIRMADA';
